### ISSUE TITLE
Issue in using enviournment variable - GITHUB_BASE_REF and GITHUB_HEAD_REF

### ISSUE THREAD

**Issue by gbohra** [Azure/cli#13]
Hi,

We are not able to use environment variable - GITHUB_BASE_REF and GITHUB_HEAD_REF in creating the slot command.
_az webapp deployment slot create_

We are using -slot along with GITHUB_BASE_REF or GITHUB_HEAD_REF. This is not passing blank value in slot name.

Can you check the issue?

Here is gist - https://gist.github.com/gbohra/c10ce7701e4fcdb2ac708a10727a870d

**Comment by gbohra** [comment]
https://gist.github.com/gbohra/c10ce7701e4fcdb2ac708a10727a870d

**Comment by anil-kumar-ma** [comment]
@gbohra : Is it resolved?

**Comment by jalajmsft** [comment]
Hey @gbohra , thank you for reporting this issue. We have made a fix to access environment variables with prefix `GITHUB_*` while executing the script  in the release [v1.0.2](https://github.com/Azure/cli/tree/v1.0.2).

However, the user-defined environment variables will be still inaccessible. We are working on this.

**Comment by anweiss** [comment]
@jalajmsft any updates on this? it's a bit kludgy to have to append `GITHUB_` to user-defined environment variables when used in an `inlinescript`

**Comment by jalajmsft** [comment]
This is resolved and deployed.

Closing this issue. Feel free to re-open for further queries.
