### ISSUE TITLE
Update Node from version 16 to version 20

### ISSUE THREAD

**Issue by arnoldknott** [Azure/cli#132]
Same issue as with azure/login@v1: https://github.com/Azure/login/issues/357

Please update to version 20, to avoid depreciation warnings:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/login@v1, azure/CLI@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by MoChilia** [comment]
Thank you for opening this issue. It's already in our plan. We will get back to you once it's done.

**Comment by longmauriceproj** [comment]
Any updates? The linked issue with azure/login has been open for months as well.
