### ISSUE TITLE
New version release with node 20 compatibility updates

### ISSUE THREAD

**Issue by longmauriceproj** [Azure/cli#139]
The latest version of the Azure CLI Action is at v1.0.9. Will we be releasing a new version to include the recent node 20 compatibility updates?

**Comment by MoChilia** [comment]
Yes, these changes have been merged into the master branch. We are currently planning to release a new version, with the latest release scheduled no later than March. I'll keep this issue open and notify you as soon as the release is ready.

**Comment by maythamfahmi** [comment]
looking forward to it being merged soon.

**Comment by MoChilia** [comment]
Hello everyone, we've just released `azure/cli@v2`. Please update your workflow to use `azure/cli@v2` to apply this change. Thank you all for your patience. Give this new version a try!
