### ISSUE TITLE
Warning: Unable to fetch all az cli versions

### ISSUE THREAD

**Issue by vn0siris** [Azure/cli#155]
Warning: Unable to fetch all az cli versions, please report it as an issue on https://github.com/Azure/CLI/issues. Output: ***
  "name": "azure-cli",
  "tags": [
    "0.10.0",
    "0.10.1",
    "0.10.10",
    "0.10.11",
    "0.10.12",
    "0.10.13",
    "0.10.14",
    "0.10.2",
    "0.10.3",
    "0.10.4",
    "0.10.5",
    "0.10.6",
    "0.10.7",
    "0.10.8",
    "0.9.10",
    "0.9.13",
    "0.9.14",
    "0.9.15",
    "0.9.16",
    "0.9.17",
    "0.9.18",
    "0.9.19",
    "0.9.2",
    "0.9.20",
    "0.9.4",
    "0.9.5",
    "0.9.6",
    "0.9.7",
    "0.9.8",
    "0.9.9",
    "2.0.24",
    "2.0.26",
    "2.0.27",
    "2.0.28",
    "2.0.29",
    "2.0.31",
    "2.0.32",
    "2.0.34",
    "2.0.37",
    "2.0.38",
    "2.0.41",
    "2.0.42",
    "2.0.43",
    "2.0.44",
    "2.0.45",
    "2.0.46",
    "2.0.47",
    "2.0.49",
    "2.0.50",
    "2.0.51",
    "2.0.52",
    "2.0.53",
    "2.0.54",
    "2.0.55",
    "2.0.56",
    "2.0.57",
    "2.0.58",
    "2.0.59",
    "2.0.60",
    "2.0.61",
    "2.0.62",
    "2.0

**Comment by MoChilia** [comment]
Hi @vn0siris, this is a duplicate issue of #153, which has been fixed in #154. You can point to `master` branch as a temporary workaround. I will inform you once the new version is released.
