### ISSUE TITLE
📢We're now open to meet and talk for GitHub Actions with you.

### ISSUE THREAD

**Issue by Jacekey23** [Azure/cli#160]
Hi,
Our team recently is opening to collect your feedback and suggestions on our GitHub Action. This helps us to value our user's input to build out more functionality based on the real detractors and delighters. 

If you'd like to talk to us, please reach out to mingxuli@microsoft.com or shiyingchen@microsoft.com and we'll make it happen!

Thanks,
Azure CLI Action team

**Comment by jakub-lesniak-ikea** [comment]
Can you please start maintaining the repositories for Github Actions for Azure? There are annoying outstanding issues and no one is even able to create a release after PRs have been merged. I.e. this: https://github.com/Azure/cli/pull/154 that has been merged over a month ago.

**Comment by MoChilia** [comment]
Hi @jakub-lesniak-ikea, apologies for the wait. We'll release a minor update this week. Thank you.

**Comment by MoChilia** [comment]
@jakub-lesniak-ikea, `azure/cli@v2.1.0` is now available. Would you like to give it a try? I'll update the `v2` tag to point to this release on Wednesday, provided no issues arise.
