### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by trendoid** [Azure/cli#19]
This used to work as recently as yesterday.  It's no longer working.  Would you have any advice?

name: Publish styles
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: 

`az storage blob upload-batch -s $GITHUB_WORKSPACE/.out-styles -d ui-component-library/styles/${{ steps.publishVersion.outputs.version }} --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --account-key ${{ secrets.STORAGE_ACCOUNT_KEY }}`

Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
The command failed with an unexpected error. Here is the traceback:

[Errno 2] No such file or directory: 'ui-component-library/styles/2-2-3'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)

**Comment by bishal-pdMSFT** [comment]
`ui-component-library/styles/2-2-3` seems to be a file/directory in your package. Is this really existing?

**Comment by trendoid** [comment]
@bishal-pdMSFT   ui-component-library/styles/2-2-3  is the destination folder.  It exists.  The same exact command works locally.  It has worked for over 400 times in the past without fail.

![image](https://user-images.githubusercontent.com/7746539/89337556-1c202400-d669-11ea-9aed-a462b379cb64.png)

**Comment by trendoid** [comment]
specific cli version fixed it.

name: Publish styles
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: 2.9.1
        inlineScript:

**Comment by trendoid** [comment]
@bishal-pdMSFT    Another developer on our team @cjc061000 pointed out that Azure released today.  So just using a CLI version older than today worked.

![image](https://user-images.githubusercontent.com/7746539/89340429-bb471a80-d66d-11ea-8034-321b6c56a791.png)

**Comment by bishal-pdMSFT** [comment]
Glad that the Action is serving its purpose by allowing you to choose an older version 😄 

I would suggest to open an issue with Az CLI product for issue with latest version.

**Comment by trendoid** [comment]
I will have to update locally to help them test but I will in the morning.

**Comment by trendoid** [comment]
This can now close.  Thanks.
