### ISSUE TITLE
Support `echo "{name}={value}" >> $GITHUB_ENV` pattern instead of deprecated `echo ::set-env name={name}::{value}` pattern

### ISSUE THREAD

**Issue by vida-bandara-by** [Azure/cli#23]
Currently, to pass a value from Azure CLI Action step to a following step, the following pattern have to be used:
`echo ::set-env name={name}::{value}`
However, `set-env` is deprecated as explained here
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Could you please support the following pattern for exporting environment variables
`echo "{name}={value}" >> $GITHUB_ENV`
explained in
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
thank you!

**Comment by bishal-pdMSFT** [comment]
@vida-bandara-by are you talking about the doc which use `set-env` is example?

**Comment by vida-bandara-by** [comment]
Hi @bishal-pdMSFT, I am not raising an issue on the doc.
This is regarding the functionality of the Azure CLI GitHub Action.

If we need to export an environment variable from a step using Azure CLI GitHub Action, we have to use the pattern:
`echo ::set-env name={name}::{value}`
But that pattern is deprecated (please see link above).

I am requesting to support pattern
`echo "{name}={value}" >> $GITHUB_ENV`
to export environment variables from a Azure CLI GitHub Action step.

Thank you!

**Comment by Weyker** [comment]
Hi, same problem here
the `::set-env name={name}::{value}` pattern is deprecated and we have broken CI on our services.

we already change to `echo "{name}={value}" >> $GITHUB_ENV` pattern but Azure CLI GitHub Action throw this error:
```
/_temp/AZ_CLI_GITHUB_ACTION_1605812805194.sh: line 2: /home/runner/work/_temp/_runner_file_commands/set_env_ee25eff9-c1b8-4e8d-b817-bf1a399799cb: No such file or directory
Error: Error: az cli script failed.
```

Thanks!

**Comment by bishal-pdMSFT** [comment]
Thanks @vida-bandara-by @Weyker for more details. We are looking into this.

**Comment by deep-mm** [comment]
Yes I have the same issue. My previous workflow used set-env, but since it is no longer valid
I am unable to set environment variables in azure cli using echo "{name}={value}" >> $GITHUB_ENV

Please update this

**Comment by Weyker** [comment]
@deep-mm meanwhile u can use the ACTIONS_ALLOW_UNSECURE_COMMANDS flag and use the deprecated way.

**Comment by kanika1894** [comment]
The support for GITHUB_ENV pattern is now added.
 @vida-bandara-by @Weyker @deep-mm Please verify.

**Comment by deep-mm** [comment]
Thank you for such a swift fix! It’s working for me now.

**Comment by vida-bandara-by** [comment]
Thank you @kanika1894 for the fix. Confirmed it is working now. Closing the issue.
