### ISSUE TITLE
Misleading docs: Azure Login is NOT required

### ISSUE THREAD

**Issue by reilem** [Azure/cli#32]
The following section of the docs states that:

> Dependencies on other GitHub Actions
> 
> Azure Login – Required Login with your Azure credentials
> Checkout – Optional To execute the scripts present in your repository

As a new user to azure, this is simply false and confusing, you do not need azure login if your AZ command works using connections strings and keys. I strongly advise against making people add an extra 10 seconds to their github actions for no reason. It is also just a good idea in general to use anonymous keys in your CI/CD which can easily be reset if compromised. Misleasing users of this action into thinking they need to perform some sort of login (even if it is just with tightly scoped service principal) is needlessly risky. I suggest changing the docs to something like:

> Dependencies on other GitHub Actions
> 
> Azure Login – [Optional] Login with your Azure credentials, required only for authentication via azure credentials. Authentication via connection strings or keys do not require this step.
> Checkout – [Optional] To execute the scripts present in your repository

**Comment by kanika1894** [comment]
@pulkitaggarwl Can you please take care of this?

**Comment by N-Usha** [comment]
Thanks @reilem. Using Azure login is a pre-req if you are deploying to any Azure source using one of our [GH Actions for Azure](https://github.com/Azure/actions).  For Az CLI, the same pre-req applies. Additionally you could override the login by doing additional login step within the Az CLI script. 

@kanika1894 - Can you please validate if the suggestion provided by @reilem is valid? Would the CLI action work w/o the pre-req of Azure login action?

**Comment by reilem** [comment]
@N-Usha For example, the following would not require a login, it is authorised using a connection string:
```
- uses: azure/cli@v1
  with:
    azcliversion: ${{ env.AZ_CLI }}
    inlineScript: |
      az storage blob upload-batch -d mycontainer -s <path-to-directory> --connection-string <authorization-string>
```
This is just one example, there are many az commands using connection strings, tokens, keys, etc. that do not require login.

**Comment by Crisfole** [comment]
I can confirm this works as I have a script using almost exactly this az command. It's still painfully slow (32 seconds to run the upload-batch to azure, vs 4 seconds to upload the same batch of files to s3).

**Comment by t-dedah** [comment]
Merged the PR for this https://github.com/Azure/cli/pull/51
