### ISSUE TITLE
Bicep support

### ISSUE THREAD

**Issue by mdmsua** [Azure/cli#35]
When I try to deploy or validate a bicep template, I'm getting the following error:
```
Run azure/cli@v1
  with:
    inlineScript: az deployment group validate -g contoso -f ./main.bicep
    azcliversion: latest

Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
ERROR: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /root/.azure/bin/bicep)
Error relocating /root/.azure/bin/bicep: __isnanf: symbol not found
Error relocating /root/.azure/bin/bicep: sysctl: symbol not found
Error relocating /root/.azure/bin/bicep: __isnan: symbol not found
Error relocating /root/.azure/bin/bicep: __strdup: symbol not found

Installing Bicep CLI v0.3.1...
Successfully installed Bicep CLI to "/root/.azure/bin/bicep".

Error: Error: az cli script failed.
```

Apparently, Bicep CLI installation succeeds, but nevertheless the build fails.

The same error occurs with `az bicep install` and `az bicep build` commands.

**Comment by sebader** [comment]
+1 on this :)

**Comment by shenglol** [comment]
This is a known issue reported in the Bicep repo: https://github.com/Azure/bicep/issues/1683. It has already fixed by https://github.com/Azure/azure-cli/pull/17180. The next release of Azure CLI should contain the fix.

**Comment by miqm** [comment]
Until cli fix and next version of bicep with musl build are released you can use my simple docker image where I used debian instead alpine as a base image: https://hub.docker.com/r/miqm/bicep-cli

**Comment by shenglol** [comment]
This should be fixed with the latest Azure CLI and Bicep releases.

**Comment by mdmsua** [comment]
Yes, I've just tested and can confirm: it's working! 🎉
