### ISSUE TITLE
Easier to identify container based action

### ISSUE THREAD

**Issue by romerve** [Azure/cli#36]
Hi,

I know that there is a NOTE in the docs about this action mentioning that it is docker based, but this should be towards the top. Or provided via a tag or something that easily allows to identify container based actions.

Thanks

**Comment by anuragc617** [comment]
@N-Usha should we add tag or modify doc to tell user's that this is an container based action?

**Comment by t-dedah** [comment]
Merged the PR for this change https://github.com/Azure/cli/pull/51
