### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Crisfole** [Azure/cli#37]
I tried using azure/cli to upload a batch of files to Azure Storage. Unfortunately it takes 33 seconds to upload a single mid-size file. That's down from 55 seconds when I follow the instructions in the repo that suggest azure/login is mandatory first. It's 29 second longer than it takes me to upload the files to s3 with https://github.com/shallwefootball/upload-s3-action.

I may be using azure/cli when a node script would be more appropriate. If so that guidance would be useful both here in this issue, and on the azure/cli README.

**Comment by t-dedah** [comment]
Hi @Crisfole , We have updated the readme making az login as an optional step depending upon the use case.

**Comment by t-dedah** [comment]
Closing this issue for now. Please reopen if you have more followup questions.
