### ISSUE TITLE
('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e632dfdd8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

### ISSUE THREAD

**Issue by neil-n-brown** [Azure/cli#40]
Having issues logging into Azure via the Azure CLI on a linux machine. No issues from my Windows Machine on the same network.

I am behind a Corp Proxy and same Env settings work for windows machine but not Linux.

****Error ****
('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e632dfdd8

When I use: az login --use-device-code I get the device code back from the terminal but once I enter it into the web page I get the error above

When I login by Service Principal I get the error straight away.

**Steps Taken Already**

1.	We have set the http_proxy and https_proxy environment variables as shown in the Working behind a proxy section of the Azure CLI documentation:  Use Azure CLI effectively | Microsoft Docs. 

Proxy Settings:
http_proxy=http://HKG\username:<password removed>@ourproxy:8080>
https_proxy=https://HKG\username:<password removed>@ourproxy:8080>
no_proxy=.microsoftonline.com,.microsoft.com,.windows.net,.azmk8s.io,.azurecr.io 

 
2.	I also appended our MHSA CA and Proxy Cert to the cacert file used by the Azure CLI as instructed in the docs if we encounter any issues with connectivity.

/usr/lib/python3.6/site-packages/pip/_vendor/certifi/cacert.pem
/usr/lib/python3.6/site-packages/pip/_vendor/requests/cacert.pem
/usr/lib64/az/lib/python3.6/site-packages/certifi/cacert.pem
/usr/lib64/az/lib/python3.6/site-packages/pip/_vendor/certifi/cacert.pem
/usr/lib64/az/lib/python3.6/site-packages/websocket/cacert.pem
/usr/local/lib/python3.6/site-packages/certifi/cacert.pem
/usr/local/lib/python3.6/site-packages/websocket/cacert.pem

3. Confirmed curl to webpages is okay and also confirmed no issue with nslookups to proxy server or internet destinations

**System Versions**

az version:
{
  "azure-cli": "2.23.0",
  "azure-cli-core": "2.23.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

OS Version:  Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Suspected Root Cause**
It appears that the Python under the hood of Azure CLI is not picking up the proxy env variables when it needs to. The no_proxy variables do not seem to have an issue as when they included added I am able to launch the device login page. Without these settings I am not able to launch the device login instead I get slightly different error:

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/devicecode?api-version=1.0 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f452ae3ff60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)))

But the no_proxy settings are standard for my environment as this is what I use on my windows machine and I connect via device login or service principal without issue.

**Azure CLI Install Method**

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=dnf

Followed the instructions to build from source as I do not have the dnf package manager i.e.:
curl -sL https://azurecliprod.blob.core.windows.net/rhel7_6_install.sh | sudo bash

**Comment by t-dedah** [comment]
Hey @neil-n-brown  can you confirm if the DNS being used is correctly configured ?

**Comment by neil-n-brown** [comment]
Hi @t-dedah sorry for the reply time. DNS configured correctly. Bit of a strange one. I was able to get it working my adding the proxy variables in both lower case and upper case.

Proxy Settings:
http_proxy=http://HKG\username:@ourproxy:8080>
https_proxy=https://HKG\username:@ourproxy:8080>
no_proxy=.microsoftonline.com,.microsoft.com,.windows.net,.azmk8s.io,.azurecr.io
HTTP_PROXY=http://HKG\username:@ourproxy:8080>
HTTPS_PROXY=https://HKG\username:@ourproxy:8080>
NO_PROXY=.microsoftonline.com,.microsoft.com,.windows.net,.azmk8s.io,.azurecr.io

**Comment by neil-n-brown** [comment]
issue resolved by adding upper and lower case proxy settings.
