### ISSUE TITLE
Why is the Azure CLI action only available on Linux based runners?

### ISSUE THREAD

**Issue by simonech** [Azure/cli#54]
I tried running the AZ command using the AZ CLI action and I got the following error:

```
Please use Linux based OS as a runner.
```

I'm wondering why enforcing Linux based runners and not allowing windows runner. I ran the same az command with the `run` command and it worked fine on Windows

**Comment by t-dedah** [comment]
Hi @simonech The docker container which is used to run the commands is only available for linux. If we try to pull that container from mcr in a windows machine which is using windows version of docker then this error is thrown.

```
Unable to find image 'mcr.microsoft.com/azure-cli:latest' locally
latest: Pulling from azure-cli
docker: image operating system "linux" cannot be used on this platform.
See 'docker run --help'.
```

**Comment by t-dedah** [comment]
Closing this issue for now. Please reopen if you have more followup questions.

**Comment by populov** [comment]
@t-dedah Are there any plans for Windows runners support?
