### ISSUE TITLE
Update tag 1.0.4 to be v1.0.4

### ISSUE THREAD

**Issue by philip-gai** [Azure/cli#55]
See most recent tag: https://github.com/Azure/cli/releases/tag/1.0.4

Does not follow the naming convention of the rest of the tags: https://github.com/Azure/cli/tags

**Comment by t-dedah** [comment]
@philip-gai  We released a new version for the action with v1.0.5, do you still feel the need for the above change?

**Comment by philip-gai** [comment]
> @philip-gai We released a new version for the action with v1.0.5, do you still feel the need for the above change?

No it's just a nit, no big deal 😄 

Thanks!

**Comment by t-dedah** [comment]
Closing this issue as updating older tag might break current user scenarios and we also released a new version with proper tag.
