### ISSUE TITLE
--sdk-auth deprecated warning

### ISSUE THREAD

**Issue by devlead** [Azure/cli#66]
In repo README you state
```bash
az ad sp create-for-rbac --name "myApp" --role contributor \
                            --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} \
                            --sdk-auth
```

Running this command now gives a deprecated warning.

> October 21, 2021
> Role
>
>    az ad sp create-for-rbac: Deprecate --sdk-auth

https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#role

What do you recommend one use instead?

**Comment by t-dedah** [comment]
Hi @devlead, we are trying to get more clarity on this from azure team, will update you once we have all the information.

**Comment by devlead** [comment]
> Hi @devlead, we are trying to get more clarity on this from azure team, will update you once we have all the information. 

Ok thanks 👍

**Comment by glloydcorecard** [comment]
has there been any update on this?

**Comment by t-dedah** [comment]
hI @devlead @glloydcorecard 👋 the above mentioned command is used to generate credentials which are needed by `azure/login` for proper authentication. As `azure/login` doesnt support the new format without `--sdk-auth`, we cannot move forward with read me changes. There is an issue opened with `azure/login` for the same https://github.com/Azure/login/issues/190

**Comment by t-dedah** [comment]
Closing this issue now. Please track the status of `--sdk-auth` deprecation for `azure/login` [here](https://github.com/Azure/login/issues/190)

**Comment by jonathan-boudreau-work** [comment]
Hello, I'm getting a 404 with the link provided and will be affected by this once it takes effect.
