### ISSUE TITLE
IPV4 or CIDR for Storage, event hub etc

### ISSUE THREAD

**Issue by Ehsaan-Azizi** [Azure/cli#70]
hi, 
I am trying to add 2 IP or CIDR ranges to my storage account or event hub namespsace in this case using az cli but it won't let me add more than one at a time. I am using this following command: 
az eventhubs namespace network-rule add \
                                        --namespace-name ns-name \
                                        --resource-group rg-name
                                        --ip-address 10.1.0.0/16,162.168.0.0/24 (allows me add one IP, how can I add more IPs here?)
I keep getting this error when I add more than one IP: 
ERROR: BadRequest: The provided ip address mask does not follow the CIDR notation.

When I run the command twice with separate IPs then it works fine but I don't want that. I want to be able to add more IPs to one single command such as above az cli script. Any ideas? Thanks!

**Comment by t-dedah** [comment]
Hi @Ehsaan-Azizi, are you able to run the above script with azure cli in the terminal?

**Comment by Ehsaan-Azizi** [comment]
Hi Deepak,
Sorry for the late reply, yes I can run it in the terminal but it won't let me put more than one subnet.

Regards,

Ehsan Azizi, MS CS
Engineer | IT Infrastructure
________________________________

**Comment by Ehsaan-Azizi** [comment]
Hi there,
This issue should not be stale since I replied earlier this month. I still haven't resolved the issue. Please advise!

**Comment by t-dedah** [comment]
Hi @Ehsaan-Azizi 

> Sorry for the late reply, yes I can run it in the terminal but it won't let me put more than one subnet.

If I understand correctly you are not able to run the command even from azure-cli in your terminal. That means the issue if with the underlying cli itself. I have raised an issue with azure-cli team as this repo is for the action based on azure-cli rather than azure-cli itself.

https://github.com/Azure/azure-cli/issues/21098

**Comment by t-dedah** [comment]
Hi @Ehsaan-Azizi are you still facing this issue? If no then should I go ahead and close the issue. Any further azure-cli related conversation can continue on the issue  created with `azure-cli` team here https://github.com/Azure/azure-cli/issues/21098
