### ISSUE TITLE
azure-mgmt-monitor 4.0.1 might be causing azure ext repo PRs to fail validation in py3.6

### ISSUE THREAD

**Issue by swells** [Azure/cli#80]
Perhaps commit: https://github.com/Azure/azure-cli/commit/76c224121c05f77f6cf6f17130b6c8fde824e10a  is causing build issues in the azure-cli-extensions repo during ext PRs. This worked ok last week. 

Impact is that it is failing and preventing ext's from successfully merging PRs hence can not publish ATM.

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/1356351/183712226-e693d78c-6ff7-439f-bff1-0dd4a7c63653.png">

**Comment by bishal-pdMSFT** [comment]
@swells I did not get how this repo is connected to the failure. The commit you mention is in https://github.com/Azure/azure-cli repo. Perhaps that's where the issue should go to.

**Comment by swells** [comment]
@bishal-pdMSFT  -- you are correct. I will close and transfer.
