### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by NaveenTSW** [Azure/cli#89]
See warnings for Node12 deprecation

"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: azure/CLI"

the action snippet which is complaining about Node12.
uses: azure/CLI@v1
with:
azcliversion: latest
inlineScript: |

**Comment by nosvalds** [comment]
Looks like this is being worked on: https://github.com/Azure/cli/pull/85

**Comment by NaveenTSW** [comment]
yeah thanks @nosvalds , not sure who takes the cut from the merge done https://github.com/Azure/cli/pull/85 and tags new version.

**Comment by NaveenTSW** [comment]
as this is getting addressed as part of https://github.com/Azure/cli/pull/85 , closing this
